### ISSUE TITLE
Can't get USB to boot

### ISSUE THREAD

**Issue by tylandercasper** [randyzhong/OS-X-HP-EliteDesk-800-G2-DM-Clover#2]
I'm trying to install Mac os X on my computer, but I can't even get it to boot into the clover bootloader. 
I've tried to installation from this guide: https://github.com/sakoula/HP-EliteDesk-800-G2-6700#preparing-usb-flash-drive but had no luck. 
What's the exact steps I should use to install your files and clover onto a USB drive to make it work?

It's my first time installing a hackintosh so sorry if this is supposed to be obvious.

**Comment by tylandercasper** [comment]
> Nevermind. The issue was that when I formatted the usb drive it didn't put the GUID table on it so there was no EFI partition to boot from.

**Comment by randyzhong** [comment]
Glad to know that you fix it.
