### ISSUE TITLE
usb3.0不能识别

### ISSUE THREAD

**Issue by wmlunge** [randyzhong/OS-X-HP-EliteDesk-800-G2-DM-Clover#3]
这个EFIUSB3.0正常但前面板耳机和话筒公共接口有问题
https://github.com/lilmik/HP-800G2-DM-Hackintosh

**Comment by randyzhong** [comment]
可以再具体点吗？包括你的机型，macOS版本，35W还是65W机器，接入的USB3.0是什么设备，是前置还是后置USB3.0接口等等

**Comment by wmlunge** [comment]
机器是 hp Mp9 G2 DM （35W）和800G2 硬件一样少无线网卡
macOS版本：10.15.7 (19H15)
CPU：6600T
内存 ：8G
网卡：bcm943224PCIEBT2+m.2转接卡（需要添加驱动 AirportBrcmFixup.kext，BrcmFirmwareData.kext，BrcmPatchRAM2.kext）
USB3.0问题已经解决，（闪迪 CZ74 64G）解决方法：
内核与驱动补丁：
添加
名称                                                                                            查找                              替换
 com.apple.driver.AppleIntelSKLGraphicsFramebuffer         0F828F03 0000         0F820000 0000

现在USB3.0 U盘插上直接显示，但是前面板的耳机和话筒那个孔插上耳机没反应
还改了引导参数
 -igfxnohdmi
-lilubetaall
brcmfx-country=#a

**Comment by randyzhong** [comment]
前置的麦克风/耳机二合一接口暂时无法驱动。
PS. USB 3.0 的问题在 2020年11月15日 的更新中应该已经解决。
