### ISSUE TITLE
"An Error occurred while preparing the installation"

### ISSUE THREAD

**Issue by ALAN84172** [randyzhong/OS-X-HP-EliteDesk-800-G2-DM-Clover#4]
I get all the way into the installer but right near the end of the installation I get the above message. Any idea what i might be doing wrong?

**Comment by randyzhong** [comment]
Can you post your specifications and macOS version you are trying to install?

**Comment by ALAN84172** [comment]
Thanks for responding. I worked it out in the end I had to disbable EmuVariableUefi-64.efi which i think I saw from another post somewhere.
