### ISSUE TITLE
试了网上的各种方法，均无法消除开关机时跑代码的界面

### ISSUE THREAD

**Issue by PilotSnail** [randyzhong/OS-X-HP-EliteDesk-800-G2-DM-Clover#5]
如题，而且无法通过csrutil disable命令关闭System Integrity Protection。启动参数中的-v始终无法删除，有什么办法吗？谢谢！

**Comment by randyzhong** [comment]
你用的是 Clover 还是 OpenCore 引导？

**Comment by PilotSnail** [comment]
重新安装了系统，现在完美了，谢谢解答。

**Comment by PilotSnail** [comment]
clover
