### ISSUE TITLE
Intel8260 BT can not be found

### ISSUE THREAD

**Issue by git-ken-hub** [randyzhong/OS-X-HP-EliteDesk-800-G2-DM-Clover#6]
First thank you for the EFI, it is awesome!
My device is the same as yours, except that the specifications of CPU/MEM/HDD are different.
After using your EFI, I have manually generated a unique serial number and other numbers, and now I can successfully log in to APPLE ID and iCloud, eveything is perfect except BT.

I didn't change My wifi/BT card, yes, it is the native Intel8260.

wifi is perfect after injecting /L/E
(https://github.com/OpenIntelWireless/itlwm/releases/download/v1.3.0/AirportItlwm_v1.3.0_stable_HighSierra.kext.zip)

But BT never success, tried several times with no luck.
I used (https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/download/1.1.2/IntelBluetooth.zip).

1). I put IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext into EFI/CLOVER/Kexts/Other then reboot, nothing happens, still no BT found.

2). I use the MacOS command "log show" and grep "IntelBluetooth" to check and found nothing.

3). I use MacOS command to load manually then errors.
sudo chown -R root:wheel IntelBluetoothFirmware.kext
sudo kextload -v IntelBluetoothFirmware.kext  <--- got error
sudo chown -R root:wheel IntelBluetoothInjector.kext
sudo kextload -v IntelBluetoothInjector.kext  <-- sucessful

4). I use hacktools to check my usb port number manually, it is the same with your USBPorts.kext defined.

I don't know how to make Intel8260 BT work properly, can you share your successful experience?
This problem has bothered me for a long time, Thanks a lot!!

**Comment by randyzhong** [comment]
I don't have a WLAN/BT device on my 800G2 DM right now.
Please refer to https://github.com/randyzhong/HP-EliteDesk-800-G2-DM-Hackintosh/issues/1

Seems BT is using HS07, so you can try to modify your USB Mapping file, remove USR1 or USR2 and add HS07.

**Comment by git-ken-hub** [comment]
HI,

Finally I found the problem.
After I change the value of HS07 in your kext, the BT appearing!!!!
The point is HS07/port/Data/4bytes:0F000000 should change to HS07/port/Data/4bytes:07000000
Then reboot, it works!!
Thank you so much!!!!

However there is a problem I just found, the Type C port number seems not right, in your kext it's defined HS09
But whatever I plug iphone or ipad or any chargable device, the hacktool never detect any port signal (no light)
They can still charging, but we just don't know which port they use.
Can you share your successful experience?

Thanks a lot!!

**Comment by git-ken-hub** [comment]
These is what I found, share with you!
Have a good day~~

HS01 back left up usb2
HS02 back left down usb2
HS03 front left usb2
HS04 back right down usb2
HS05 back right up usb2
HS07 Bluetooth (IOUSBHostDevice)
HS09 TypeC+Sw (??)
HS13 front right usb2

SS01 back left up usb3
SS02 back left down usb3
SS03 front left usb3
SS04 back right down usb3
SS05 back right up usb3
SS08 front right usb3

**Comment by randyzhong** [comment]
Thanks for sharing.
I plug my Quest2 to 800g2 dm's type-c port, and it shows HS09 in Hackintool.
It's charging and I can use adb to upload files to Quest2, so I guess HS09 is correct USB type-c port on my 800g2.

Will correct my HS07 to Port 0x07 as yours. Other USB ports are the same as you posted.

**Comment by randyzhong** [comment]
Closed as no further comments.
